config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  attr_reader :password
  
  before_validation :ensure_session_token
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end
  
  def reset_session_token!
    
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    @current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username],
      params[:user][:password])

    if user.nil?
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    else
      login_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # login()
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  render :show
  end


  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1> HERE </h1>
    <% if logged_in? %>
      <%= current_user.username %>
      <form action="<%= session_url  %>" method="post">
        <% auth_token_input %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Sign Out">
      </form>
    <% else %>
      <a href="<%=user_url%>"> Sign In </a>
      <a href="<%= sessions_url %>"> Sign Up </a>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1> NEW </h1>

<h2> Sign Up </h2>
<h2> Username </h2>

<form class="" action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="username"> Username
    <input type="text" name="user[username]" value="">
  </label>

  <label for="password"> Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Create User">
</form>

app/views/users/show.html.erb
<h1> SHOW </h1>

<h1> <%= @user.username %>  </h1>
<%  %>